
import Head from 'next/head'
import styles from '../styles/Test.module.css'
import Link from 'next/link'

export default function Test() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1 className = {styles.test}>dude</h1>
    <Link href = "/">home</Link>
    </div>
  )
}
